version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Skipping tests in pre_build phase...

  build:
    commands: 
      - echo Build started on `date`
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Build completed on `date`
      - ls -lh target/

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
